version: '3'
services:
  mongo:
    image: mongo:8.0.0-rc16-jammy
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: crud-node
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    environment:
      - MONGO_URL=mongodb://mongo:27017/crud
      - NODE_ENV=production
      # - NODE_ENV=development
      - PORT=3000
      - TITLE=CRUD-Node

  frontend:
    image: karthikeya2100/crud-react:latest
    container_name: crud-react
    environment:
      - API_URL=http://localhost:3000
      # - API_URL=https://crud-app.run.place/node
      - BACKEND_FRAMEWORK=Express.js and MongoDB
      - TITLE=CRUD-Node
      - GITHUB_LINK=https://github.com/karthikeya0800/CRUD-Node
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app/dist

volumes:
  mongo-data:
